apiVersion: apps/v1
kind: Deployment
metadata:
  name: slkdfods
spec:
  replicas: 1
  selector:
    matchLabels:
      app: slkdfods
  template:
    metadata:
      labels:
        app: slkdfods
    spec:
      containers:
      - image: okteto.dev/slkdfods:latest
        name: slkdfods
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "9abb2968-c602-4570-80ae-bd47e7773cb5"
        - name: Vless_Path
          value: "/vl555"
        - name: Vmess_UUID
          value: "9abb2968-c602-4570-80ae-bd47e7773cb5"
        - name: Vmess_Path
          value: "/vm666"
        - name: Share_Path
          value: "/v2link"
